name: Nova-core file deployment prod
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          
      - name: Build project and run tests
        run: |
          mvn clean install -DskipTests

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ikaue573/nova-core .

      - name: Push Docker image
        run: docker push ikaue573/nova-core

      - name: Archive built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: project-artifact
          path: ./
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download project artifact
        uses: actions/download-artifact@v2
        with:
          name: project-artifact
          path: ./downloaded-project

      - name: Check the contents of the downloaded project
        run: ls -l ./downloaded-project

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Change directory to the downloaded project
        run: cd downloaded-project

      - name: Run tests on downloaded project
        run: |
          ./mvnw test
      - name: Run Spring application with prod profile
        run: |
          java -Dspring.profiles.active=prod -jar apibackend-0.0.1-SNAPSHOT.jar
